/// Vocal Energy — the session-pacing meter.
///
/// Duolingo's hearts exist to sell refills: run out, pay or wait. That model
/// works there because a wrong answer costs nothing physical. Voice is
/// different — a tired larynx is a real constraint, and repeatedly pushing a
/// voice that has stopped improving is how people injure themselves.
///
/// So this meter **never hard-blocks**. Running out routes the user into a
/// genuine rest exercise, which they may skip. The nudge is the product; the
/// gate would be a monetisation hook wearing a health costume, and a user who
/// learns the app blocks them to sell refills stops believing the vocal-health
/// advice too.
///
/// Pure Dart. No storage, no clock of its own — the caller supplies `now`.
library;

/// What an attempt did to the meter.
enum EnergyEvent {
  /// Scored at or above passing. Nothing spent.
  unchanged,

  /// One bar spent on a low-scoring attempt.
  spent,

  /// Two bars: a second consecutive low score on the same lesson. Repeating a
  /// lesson that is not improving is the specific pattern worth interrupting —
  /// it is usually fatigue, not inability.
  spentOnRepeat,

  /// Reached zero. The user is offered a rest exercise, never forced into one.
  depleted,
}

/// The meter's state.
class VocalEnergy {
  const VocalEnergy({
    required this.bars,
    this.lastSpentAt,
    this.consecutiveLowLessonId,
    this.consecutiveLowCount = 0,
  });

  const VocalEnergy.full()
    : bars = maxBars,
      lastSpentAt = null,
      consecutiveLowLessonId = null,
      consecutiveLowCount = 0;

  static const maxBars = 5;

  /// Score below which an attempt costs energy. Deliberately the Bronze
  /// threshold: an attempt good enough to promote should never cost anything.
  static const lowScoreThreshold = 60;

  /// Idle time that returns one bar.
  static const regenInterval = Duration(minutes: 30);

  /// 0..[maxBars].
  final int bars;

  /// When a bar was last spent. Drives regeneration.
  final DateTime? lastSpentAt;

  /// The lesson the user is currently struggling with, if any.
  final String? consecutiveLowLessonId;
  final int consecutiveLowCount;

  bool get isEmpty => bars <= 0;
  bool get isFull => bars >= maxBars;

  /// Bars regenerated by idle time, plus a full reset on a new calendar day.
  ///
  /// The daily reset is what stops the meter becoming a punishment that follows
  /// someone across days. Tomorrow always starts full.
  VocalEnergy regenerated(DateTime now) {
    final last = lastSpentAt;
    if (last == null || isFull) return this;

    if (!_sameDay(last, now)) return const VocalEnergy.full();

    final elapsed = now.difference(last);
    if (elapsed.isNegative) return this;

    final earned = elapsed.inMinutes ~/ regenInterval.inMinutes;
    if (earned <= 0) return this;

    final recovered = (bars + earned).clamp(0, maxBars);
    return VocalEnergy(
      bars: recovered,
      // Advance the clock by what was actually consumed, so partial progress
      // toward the next bar is not silently discarded.
      lastSpentAt: recovered >= maxBars
          ? null
          : last.add(regenInterval * earned),
      consecutiveLowLessonId: consecutiveLowLessonId,
      consecutiveLowCount: consecutiveLowCount,
    );
  }

  /// Applies a scored attempt.
  (VocalEnergy, EnergyEvent) applyAttempt({
    required String lessonId,
    required int score,
    required DateTime at,
  }) {
    final current = regenerated(at);

    if (score >= lowScoreThreshold) {
      // A passing attempt clears the struggle counter as well as costing
      // nothing — the user just demonstrated the lesson is not the problem.
      return (
        VocalEnergy(bars: current.bars, lastSpentAt: current.lastSpentAt),
        EnergyEvent.unchanged,
      );
    }

    final repeating = current.consecutiveLowLessonId == lessonId;
    final lowCount = repeating ? current.consecutiveLowCount + 1 : 1;
    final cost = lowCount >= 2 ? 2 : 1;

    final remaining = (current.bars - cost).clamp(0, maxBars);

    final next = VocalEnergy(
      bars: remaining,
      lastSpentAt: at,
      consecutiveLowLessonId: lessonId,
      consecutiveLowCount: lowCount,
    );

    if (remaining == 0) return (next, EnergyEvent.depleted);
    return (next, cost > 1 ? EnergyEvent.spentOnRepeat : EnergyEvent.spent);
  }

  /// Restores the meter after a completed rest exercise.
  ///
  /// Two bars, not five: enough to continue, not enough to make resting a
  /// mechanical way to farm energy. Skipping the exercise restores nothing —
  /// but skipping is always allowed, and practice is never blocked either way.
  VocalEnergy afterRest(DateTime now) =>
      VocalEnergy(bars: bars < 2 ? 2 : bars, lastSpentAt: now);

  static bool _sameDay(DateTime a, DateTime b) =>
      a.year == b.year && a.month == b.month && a.day == b.day;

  @override
  bool operator ==(Object other) =>
      other is VocalEnergy &&
      other.bars == bars &&
      other.lastSpentAt == lastSpentAt &&
      other.consecutiveLowLessonId == consecutiveLowLessonId &&
      other.consecutiveLowCount == consecutiveLowCount;

  @override
  int get hashCode => Object.hash(
    bars,
    lastSpentAt,
    consecutiveLowLessonId,
    consecutiveLowCount,
  );

  @override
  String toString() => 'VocalEnergy($bars/$maxBars)';
}
